"use client";

import Link from "next/link";
import { ArrowLeft, HelpCircle } from "lucide-react";
import { useI18n } from "@/i18n";

const FAQ_ITEMS = {
  zh: [
    { q: "我的数据安全吗？", a: "是的。你在万一呢创建的所有内容都在浏览器端用 AES-256-GCM 加密后上传。我们的服务器只存储密文，永远看不到你的明文数据。密码从不上传。" },
    { q: "如果我忘了密码怎么办？", a: "密码永远不上传服务器，所以我们无法帮你重置。如果遗忘，包括我们在内的任何人都无法解密你的数据。建议将密码保存在密码管理器中。" },
    { q: "信使什么时候会被通知？", a: "只有当你连续未登录达到设定的阈值天数（默认 180 天）后，系统才会启动通知流程。在此之前我们会多次提醒你本人。" },
    { q: "可以免费使用吗？", a: "国内站完全免费。海外站可免费创建 3 条备忘 + 1 个信使，解锁全部功能需订阅（$23/年 或 $198 终身）。" },
    { q: "如何删除我的数据？", a: "在设置页面可以随时导出或删除全部数据。如需彻底删除账户，请发送邮件至 privacy@in-case.me。" },
    { q: "万一呢是遗嘱或法律文件吗？", a: "不是。万一呢是数字资产规划工具，不构成任何法律文件。涉及重大权益事项，请咨询专业律师。" },
  ],
  en: [
    { q: "Is my data secure?", a: "Yes. All content you create is encrypted in your browser using AES-256-GCM before being uploaded. Our servers only store ciphertext — we can never see your plaintext data. Your password is never uploaded." },
    { q: "What if I forget my password?", a: "Your password never reaches our servers, so we cannot reset it. If you lose it, no one — including us — can decrypt your data. We recommend using a password manager." },
    { q: "When will my messenger be notified?", a: "Only after you've been inactive for your configured threshold period (default 180 days). We send multiple reminders to you first before notifying your messenger." },
    { q: "Is it free to use?", a: "The domestic site is completely free. The overseas site includes a free tier (3 vaults + 1 trusted contact); full access requires a subscription ($23/year or $198 lifetime)." },
    { q: "How do I delete my data?", a: "You can export or delete all your data at any time from the Settings page. For full account deletion, email privacy@in-case.me." },
    { q: "Is In Case a will or legal document?", a: "No. In Case is a digital asset planning tool. Nothing generated by this product constitutes a legal document. Consult a licensed professional for matters involving significant legal rights." },
  ],
};

export default function FAQPage() {
  const { t, lang } = useI18n();
  const items = lang === "en" ? FAQ_ITEMS.en : FAQ_ITEMS.zh;

  return (
    <div className="max-w-2xl mx-auto px-4 py-8">
      <Link
        href="/"
        className="inline-flex items-center justify-center rounded-lg h-7 gap-1 px-2.5 text-[0.8rem] hover:bg-muted hover:text-foreground transition-all mb-6"
      >
        <ArrowLeft className="w-4 h-4 mr-1" /> {t.common.back}
      </Link>
      <h1 className="text-2xl font-bold flex items-center gap-2 mb-2">
        <HelpCircle className="w-6 h-6 text-warm-500" />
        {t.legal.faqTitle}
      </h1>
      <p className="text-sm text-muted-foreground mb-8">{t.legal.faqLastUpdated}</p>

      <div className="space-y-4">
        {items.map((item, i) => (
          <details key={i} className="group border border-border/60 rounded-xl p-4 cursor-pointer hover:border-border transition-colors">
            <summary className="text-sm font-medium text-neutral-800 group-open:mb-2 list-none">
              {item.q}
            </summary>
            <p className="text-sm text-muted-foreground leading-relaxed pt-2 border-t border-border/20">
              {item.a}
            </p>
          </details>
        ))}
      </div>
    </div>
  );
}
