/**
 * English language pack — In Case (万一呢)
 * Mirror of zh.ts keys. All user-facing English strings.
 */
import type { I18nStrings } from "./zh";

const en: I18nStrings = {
  common: {
    appName: "In Case",
    appTagline: "Keep a Spare Key, Just in Case",
    skip: "Skip →",
    continue: "Continue →",
    startGuard: "Start Protecting",
    cancel: "Cancel",
    confirm: "Confirm",
    expand: "Expand to edit",
    save: "Save",
    delete: "Delete",
    edit: "Edit",
    copy: "Copy",
    back: "Back",
    loading: "Loading…",
    error: "Something went wrong",
    retry: "Retry",
    done: "Done",
    close: "Close",
    sendCode: "Send Code",
    verify: "Verify",
    logout: "Sign Out",
    export_: "Export",
    import_: "Import",
    more: "More",
    optional: "Optional",
    required: "Required",
    noData: "No data yet",
    noAccess: "No access",
    login: "Sign In",
    bound: "Linked",
    boundTooltip: "Phone/email linked",
  },

  home: {
    heroBadge: "🔐 Open-source · Zero-knowledge · We can't read your data",
    heroTitle: "Your family shouldn't have to guess your passwords after you're gone.",
    heroDesc:
      "In Case is an encrypted vault for your accounts, assets, and final messages — shared only with the people you trust, unlocked only if you can no longer check in. Set it up in 10 minutes. Hope they never need it.",

    trustEncryptLabel: "Encrypted Before It Leaves",
    trustEncryptTitle: "Your data is locked before it ever reaches us",
    trustEncryptSubtitle:
      "AES-256-GCM — the same encryption standard used by banks, militaries, and intelligence agencies worldwide",
    trustEncryptMetaphor:
      "Like sealing a letter in a safe with a code only you know, then handing the safe to a courier. The courier can't open it — and neither can we.",
    trustEncryptPoint1:
      "Everything you type is encrypted right in your browser",
    trustEncryptPoint2:
      "Your password is never uploaded — it lives only on your device",
    trustEncryptPoint3:
      "All the server receives is indecipherable random characters",

    trustBlindLabel: "We See Nothing",
    trustBlindTitle: "We don't even know what you've stored",
    trustBlindSubtitle:
      "Zero-knowledge architecture — technically impossible for anyone to peek",
    trustBlindMetaphor:
      "Like renting a safety deposit box where only you hold the key. The bank has no idea if it contains deeds, gold bars, or a blank piece of paper.",
    trustBlindPoint1: "Encryption and decryption happen only on your own device",
    trustBlindPoint2:
      "Even if the entire database is hacked and stolen — all anyone gets is meaningless ciphertext",
    trustBlindPoint3: "No backdoors. No privileged accounts. No exceptions.",

    trustExportLabel: "Always Yours",
    trustExportTitle: "What's yours stays yours, forever",
    trustExportSubtitle:
      "Export anytime · Delete completely anytime · No data lock-in",
    trustExportMetaphor:
      "A landlord can kick you out, but your suitcase goes with you. We don't lock doors or set limits — your data, your call.",
    trustExportPoint1: "Export all your content in readable format, anytime",
    trustExportPoint2:
      "Permanently delete your account and all data, leaving no trace behind",
    trustExportPoint3:
      "If we ever shut down, we'll give you advance notice to export everything — no surprises",

    feature1Title: "Digital Asset Inventory",
    feature1Desc:
      "Map out all your digital accounts — social, payments, gaming, creative. AI-guided conversation, as easy as chatting with a friend.",
    feature1Badge: "Step 1",
    feature1Cta: "Start Inventory",

    feature2Title: "Letters from the Heart",
    feature2Desc:
      "Write letters to the people who matter. The words you've been holding in — write them down. Encrypted and kept safe, until the right person opens them.",
    feature2Badge: "Step 2",
    feature2Cta: "Write a Letter",

    feature3Title: "Security Settings",
    feature3Desc:
      "Choose someone you trust — give them the unlock link and password. They can't open anything while you're active, only when you're truly unable to check in.",
    feature3Badge: "Step 3",
    feature3Cta: "Go to Settings",

    footerTagline: "Generated by {appName} · Keep a Spare Key, Just in Case",
    footerGitHub: "Open Source & Auditable · GitHub",
    footerAuthor: "Independently built and maintained by a full-stack engineer · 2026",
    footerDisclaimer:
      "This product does not constitute legal advice. Consult a licensed attorney for significant matters.",
    footerTaglineBefore: "Generated by ",
    footerTaglineAfter: " · ",
    footerCollapse: "Collapse",
    footerPrivacyLabel: "Privacy & Security",
    footerPrivacyDesc: "How we protect your data",
    trustSlideshowLabel: "Is my data safe?",
    trustSlideshowHint: "Use arrow keys to browse · Click outside to close",
    trustSlides: [
      {
        title: "You write in your browser first",
        body: "Whether it's an asset inventory or a heart letter — everything lives on your device. Nothing has ever left your browser until you press \"Encrypt & Save.\"",
      },
      {
        title: "Encryption happens before data leaves your device",
        body: "The moment you press save, AES-256-GCM encryption locks your content in your browser. It's like putting a letter in a safe, setting the code, then handing the safe to a courier. The courier can't open it — neither can we.",
      },
      {
        title: "Our servers only store ciphertext",
        body: "What reaches our servers is meaningless scrambled data. Even if the entire database were hacked and stolen — all anyone would see is indecipherable noise. There are no backdoors, no privileged accounts that can peek.",
      },
      {
        title: "You check in regularly to prove you're well",
        body: "Every so often, you press \"I'm here.\" As long as you keep renewing, anyone with the access link will be denied. Only when 90 consecutive days pass without renewal does the system consider something may have happened — and the spare key becomes active.",
      },
      {
        title: "Your trusted contact unlocks with the link + password",
        body: "You give your trusted contact the access link and decryption password ahead of time. When your protection timer expires, they open the link, receive the encrypted package, enter the password, and unlock everything in their own browser — seeing what you left for them. Throughout this entire process, we never see a single word of plaintext.",
      },
    ],
    footerTrust1Title: "Data encrypted before leaving your device",
    footerTrust1Desc:
      "All sensitive content is encrypted on your device using AES-256-GCM before being sent to the server. The server only stores indecipherable ciphertext — even if the database is compromised, your data cannot be cracked.",
    footerTrust2Title: "You own your data, absolutely",
    footerTrust2Desc:
      "We use zero-knowledge architecture. Your decryption password is never uploaded to the server. This means no one — not the developers or operators of In Case — can read your plaintext. You can export and delete your data at any time.",
    footerTrust3Title: "Supabase database, no third-party tracking",
    footerTrust3Desc:
      "Your encrypted data is stored directly in Supabase. We don't use any third-party analytics, ad trackers, or user behavior monitoring. No Google Analytics. No tracking SDKs.",
    footerTrust4Title: "Open source & auditable",
    footerTrust4Desc:
      "Our entire codebase is open source on GitHub. Security researchers and users can audit our encryption, database schema, and API logic in real time. Trust isn't built on promises — it's built on transparency.",
    openSourceSoon: "View source code on GitHub",
  },

  onboarding: {
    slide1Title: "Welcome to In Case",
    slide1Subtitle:
      "Organize your digital life.\nProtect the people and things you care about.",

    slide2Title: "Map Your Digital World",
    slide2Subtitle:
      "Social accounts, subscriptions, games, creative work.\nTake stock — so you know what needs protecting.",

    slide3Title: "But more importantly—",
    slide3Subtitle:
      "If one day you can't handle these things yourself,\nwho would you trust? What would you want them to know?",

    slide4Title: "Three Simple Steps",
    slide4Subtitle: "Hand the spare key to someone you trust",

    assetVisualLabel: "Someone you trust",
    step1Label: "Take Inventory",
    step2Label: "Write Letters",
    step3Label: "Choose Who to Trust",
  },

  renewal: {
    cardTitle: "Quick Check-In",
    title: "Still here? Let your circle know.",
    desc: "Check in regularly to confirm you're well and keep your protection active.",
    lastCheckin: "Last check-in",
    daysAgo: "{n} days ago",
    thresholdDays:
      "Protection threshold: {n} days of inactivity triggers notification",
    checkinNow: "All is well, keep watching",
    checkinSuccess: "Renewed ✓ Your protection continues",
    bindReminder:
      "Link your identity to restore your check-in status across devices",
    goBind: "Link Now",
    vaultLabel: "vaults",
    credLabel: "contacts",
  },

  bind: {
    modalTitle: "Link Your Identity",
    modalDesc:
      "Subscribe to enable alerts. If you go silent, the people you trust will be notified. Your data is encrypted — we can never access it.",
    phoneLabel: "Phone Number",
    phonePlaceholder: "Enter phone number",
    emailLabel: "Email",
    emailPlaceholder: "Enter email",
    codeLabel: "Verification Code",
    codePlaceholder: "Enter code",
    codeSent: "Code sent",
    phoneOptional: "Add your phone number",
    bindSuccess: "Linked ✓",
    bindError: "Linking failed, please try again",
    boundTitle: "Account Linked",
    boundDesc: "Log in from any device to restore all your data",
    changeBind: "Change Contact",
    unbindTitle: "Unlink",
    unbindConfirm: "Without a linked contact, you won't be able to recover data on a new device. Are you sure?",
    switchToPhone: "Use phone",
    switchToEmail: "Use email",
    codeSentToPhone: "Code sent to {target}",
    codeSentToEmail: "Code sent to {target}, please check your inbox",
  },

  inventory: {
    aiGreeting: "I'm your digital inventory assistant. I'll help you map out every account and asset you've left across the internet — one step at a time. No rush, just tell me what comes to mind.",
    title: "Digital Asset Inventory",
    navTitle: "Inventory",
    desc: "Map out all your digital accounts. Know what you have and what to protect.",
    startButton: "Start Inventory",
    chatPlaceholder: "Type your response…",
    send: "Send",
    regenerating: "Regenerating…",
    regenerate: "Try Again",
    saveToVault: "Save to Vault",
    saveSuccess: "Saved to vault ✓",
    savedAssets: "{n} assets inventoried",
    noAssets: "No assets inventoried yet",
    categories: {
      finance: "Finance",
      investment: "Investment",
      creator: "Creator",
      gaming: "Gaming",
    },
    categoryTabs: {
      finance: "💰 Finance",
      investment: "📈 Investment",
      creator: "🎬 Creator",
      gaming: "🎮 Gaming",
    },

    financeLabel: "Platform / Institution",
    financePlaceholder: "e.g. Chase, Bank of America, PayPal…",
    financeAccountLabel: "Account / Card (last 4 digits)",
    financeAccountPlaceholder: "e.g. ending xxxx, linked to +1xxxx",
    financeChannelNote: "No need to fill in the access process. When your trusted contact retrieves these, the platform auto-generates a step-by-step guide based on each institution's latest policies.",
    financeActions: {
      withdraw: "Withdraw",
      undecided: "Undecided",
      custom: "Custom",
    },

    investmentLabel: "Platform / Broker",
    investmentPlaceholder: "e.g. Robinhood, Fidelity, Coinbase…",
    investmentTypeLabel: "Type",
    investmentTypePlaceholder: "e.g. US stocks, crypto, ETFs, mutual funds",
    investmentScaleLabel: "Approx. Scale (range is fine)",
    investmentScalePlaceholder: "e.g. $5-10K, or 0.5 BTC",
    investmentChannelNote: "No need to fill in the access process. When your trusted contact retrieves these, the platform auto-generates a step-by-step guide based on each institution's latest policies.",
    investmentActions: {
      cashOut: "Cash Out",
      hold: "Leave As Is",
      undecided: "Undecided",
      custom: "Custom",
    },

    creatorLabel: "Platform",
    creatorPlaceholder: "e.g. YouTube, TikTok, Substack, Instagram…",
    creatorAudienceLabel: "Audience / Reach",
    creatorAudiencePlaceholder: "e.g. 100K subscribers, ~500K monthly views",
    creatorIncomeLabel: "Revenue Sources",
    creatorIncomePlaceholder: "e.g. AdSense linked to Chase xxxx, brand deals via PayPal",
    creatorBusinessLabel: "Business Contacts",
    creatorBusinessPlaceholder: "e.g. Brand X contact: John +1xxxx, contracts in Google Drive",
    creatorAssetsLabel: "Content Assets",
    creatorAssetsPlaceholder: "e.g. project files in Dropbox, music rights purchased",
    creatorDisposalLabel: "Disposal Plan",
    creatorDisposalPlaceholder: "e.g. transfer operation, keep running, or shut down",
    creatorActions: {
      transfer: "Transfer Operation",
      continue: "Keep Running",
      delete: "Shut Down",
      undecided: "Undecided",
      custom: "Custom",
    },

    gamingLabel: "Platform / Game",
    gamingPlaceholder: "e.g. Steam, Minecraft, Fortnite, RuneScape…",
    gamingValueLabel: "Account Value (approx.)",
    gamingValuePlaceholder: "e.g. library worth ~$400, or ~$5K in purchases",
    gamingBindLabel: "Linked Accounts",
    gamingBindPlaceholder: "e.g. Steam Guard, phone, email",
    gamingDisposalLabel: "Disposal Plan",
    gamingDisposalPlaceholder: "e.g. give away, sell, memorialize, or delete",
    gamingActions: {
      transfer: "Give Away",
      sell: "Sell",
      memorialize: "Memorialize",
      delete: "Delete",
      undecided: "Undecided",
      custom: "Custom",
    },

    customActionPlaceholder: "Describe how you want it handled…",
    actions: {
      keep: "Keep",
      transfer: "Transfer",
      delete: "Delete",
      undecided: "Undecided",
    },
    exportCSV: "Export CSV",
    summary: "Inventory Summary",
    hintText: "Record clues, not balances. Your family uses these clues to go through the legal inheritance process.",
    valueTipTitle: "💡 What this page does",
    valueTipBody: "You're mapping your digital world. What you record are clues (which platform, what account) — not balances. In Case organizes your clues by category. For finance and investment, we auto-generate step-by-step access guides when your trusted contact needs them. For creator and gaming, just leave login info for them. You leave the clues — we and the person you trust most will handle the rest.",
    directMode: "Manual Entry",
    aiMode: "AI-Assisted",
    notesLabel: "Notes for your trusted contact (optional)",
    notesPlaceholderFinance: "e.g. Chase checking + savings, PayPal linked, call 1-800-xxx for access",
    notesPlaceholderInvestment: "e.g. Robinhood has US stocks, Fidelity 401k, contact broker for transfer",
    notesPlaceholderCreator: "e.g. YouTube channel with AdSense, brand deals in GDrive, contact manager xxx",
    notesPlaceholderGaming: "e.g. Steam library worth ~$400, Epic account linked to email xxx@gmail.com",
    savedHint: "Encrypted & saved! Add another",
    unnamedPlatform: "Untitled",
    saveTriggerLabel: "🔒 Encrypt & Save",
    platformRequired: "Please fill in the platform name first",
    addedToList: "Added to list",
    aiChatPlaceholder: "Type your message…",
    aiChatHint: "Press Enter to send · Chat ends when complete, then encrypt & save",
    saveAllLabel: "🔒 Encrypt & Save All to Vault",
    saveAllSuffix: "Inventory",
    nextStepLetters: "Next: Write a Heart Letter",
    savedCountHint: "{n} accounts inventoried",
  },

  letters: {
    aiGreeting: "I'm your writing companion. No pressure — you're not writing a letter that needs to be sent. You're just putting the words in your heart down somewhere safe. I'm here with you.",
    title: "Letters from the Heart",
    valueTipTitle: "💡 What this page does",
    valueTipBody: "Write a letter to someone who matters. Two ways: write it yourself — just a few words from the heart; or let AI chat with you, easy as talking to a friend. Once written, it's encrypted before saving — your password is never uploaded, known only to you and the person you've chosen. No one can open it until your protection timer runs out, then they unlock it in their own browser and see what you left them.",
    desc: "Words for the ones who matter. Write them down, keep them safe.",
    startButton: "Write a Letter",
    chatPlaceholder: "Write what's on your mind…",
    draftReady: "Here's a draft for you 💌",
    draftDesc: "Edit, copy, or ask me to write another version.",
    recipient: "Recipient",
    relationship: "Relationship",
    saveDraft: "Save Draft",
    letterSaved: "Letter saved ✓",
    noLetters: "No letters yet",
    lettersCount: "{n} letters written",
    editDraft: "Edit Draft",
    deleteDraft: "Delete Draft",
    deleteConfirm: "Are you sure you want to delete this letter?",
    encryptNotice:
      "This content will be encrypted in your browser. Your password is never uploaded.",
    directMode: "Write Directly",
    aiMode: "AI-Assisted",
    recipientLabel: "To",
    recipientPlaceholder: "e.g. Mom, my future self, the person I trust most…",
    bodyLabel: "What you want to say",
    bodyPlaceholder: "Write what's on your mind. The words you've been holding in — write them down. Encrypted and kept safe, until the right person opens them.",
    savedHint: "Encrypted & saved",
    aiDraftLabel: "AI Draft",
    aiChatPlaceholder: "Who do you want to write to…",
    importantPerson: "Someone Important",
    saveTriggerLabel: "🔒 Encrypt & Save",
  },

  settings: {
    title: "Security Settings",
    navTitle: "Security",
    valueTipTitle: "💡 What this page does",
    valueTipBody: "Set up your protection in three steps: ① Choose someone you trust — give them the access link and decryption password; they'll get a notification to confirm. ② Adjust your protection threshold — how many days of inactivity before notifications begin. ③ Export an encrypted backup — your data, always yours to take. Once these three steps are done, your protection is active.",
    desc: "Manage your trusted contacts, security threshold, and data export.",

    thresholdTitle: "Protection Threshold",
    thresholdDesc:
      "After this many days of inactivity, the notification process begins.",
    thresholdUnit: "days",
    thresholdOptions: {
      30: "30 days",
      60: "60 days",
      90: "90 days",
      180: "180 days",
      365: "365 days",
    },
    thresholdSaved: "Threshold updated ✓",
    subscribedToast: "Subscription activated!",

    messengerTitle: "Trusted Contacts",
    messengerDesc:
      "Designate people you trust. They can only access anything when you're truly unable to check in.",
    addMessenger: "Add Contact",
    messengerName: "Name",
    messengerNamePlaceholder: "e.g. Mom, David",
    messengerEmail: "Email",
    messengerPhone: "Phone (optional)",
    messengerRelation: "Relationship",
    messengerRelationPlaceholder: "e.g. Family, Best friend",
    messengerCreated: "Contact added — invitation sent.",
    messengerDeleted: "Contact removed.",
    noMessengers: "No trusted contacts yet",
    messengerCount: "{n} trusted contact(s)",
    messengerNotifyNotice:
      "After adding a contact, we'll send them a note letting them know you've chosen them — nothing to do right now.",
    credentialStatus: {
      active: "Active",
      revoked: "Removed",
      delivered: "Delivered",
    },

    encryptionTitle: "Encryption Demo",
    encryptionDesc:
      "Type anything to see what it looks like encrypted — then decrypt it back.",
    encryptInput: "Type something to encrypt…",
    encrypt: "Encrypt",
    encryptedResult: "Encrypted (ciphertext)",
    decryptPassword: "Enter password to decrypt…",
    decrypt: "Decrypt",
    decryptedResult: "Decrypted",
    encryptDone: "Encrypted ✓",
    encryptHttpsRequired: "Encryption demo requires HTTPS (auto-enabled in production)",
    encryptRealtimeLabel: "AES-256-GCM Real-time Encryption",
    encryptServerView:
      "☝ This is all the server ever 'sees' — even if the database is breached, it's just indecipherable noise",

    exportTitle: "Data Export",
    exportDesc:
      "Export everything anytime. Your data belongs to you, always.",
    exportButton: "Export All Data",
    exportSuccess: "Export complete",
    deleteAccount: "Delete Account",
    deleteAccountDesc:
      "Permanently delete all your data, leaving no trace. This cannot be undone.",
    deleteAccountButton: "Permanently Delete Account",
    deleteAccountConfirm:
      "I confirm I want to permanently delete my account and all data",

    backupTitle: "Backup & Restore",
    backupDesc: "Download an encrypted backup, or restore from one.",
    backupDownload: "Download Encrypted Backup",
    backupRestore: "Restore from Backup",
    backupRestoreDesc: "Select your backup file and enter the password.",
    exporting: "Exporting…",
    exportBtn: "Export JSON",
    importing: "Importing…",
    importBtn: "Upload & Restore",
    exportFail: "Export failed, please try again",
    exportDone: "Backup downloaded! Keep it somewhere safe.",
    importDone: "Restore complete!",
    importFail: "File parsing failed. Please confirm this is a valid In Case backup JSON file.",
    importFormatError: "Invalid file format",
    importGenericFail: "Import failed",
  },

  unlock: {
    title: "Access Digital Assets",
    desc: "Enter the password you received to decrypt the contents entrusted to you.",
    passwordPlaceholder: "Enter decryption password",
    unlock: "Unlock",
    unlocking: "Unlocking…",
    wrongPassword: "Incorrect password. Please try again.",
    tooManyAttempts: "Too many attempts. Please try again later.",
    noCredential: "Link is invalid or has expired.",
    unlocked: "Decrypted successfully",
    copyContent: "Copy Content",
    downloadContent: "Download",
    aiGuideTitle: "Platform Access Guides",
    aiGuideDesc:
      "Step-by-step instructions for accessing or closing accounts on each platform, generated by AI based on the asset inventory.",
    aiGuideGenerating: "Generating access guides…",
    aiGuideDisclaimer:
      "These guides are AI-generated for reference only. Follow each platform's latest official procedures.",

    envelopeSealHint: "Tap to open",
    envelopeSubtitle: "A message left for you",
    envelopePreviewSubtitle: "Preview — what your trusted contact will see",
    letterGreetingHasName: "Dear {name}{relation},",
    letterGreetingNoName: "You're reading a letter from someone who trusts you. There are things they wanted to say, and things they wanted to entrust to you.",
    letterBodyHasName: "You're reading a letter from someone who holds you in the deepest place of their heart. There are things only you deserve to hear, things only you were meant to keep. Not because you can fix anything — but because you are worthy of their trust.",
    letterBody2: "What follows was written by them, word by word. We never saw it. We never will. Now, it's yours.",
    letterClosing: "—— In Case",
    letterContentsLabel: "What They Left for You",
    letterGuideTransition: "You don't have to do this alone. Every platform has people whose job is to help you through this — below are their contact details and the steps you'll need. One at a time.",
    letterGuideBtn: "View Platform Access Guide",
    letterGuideLoading: "Preparing your guide…",
    letterFinalLine: "That's everything. You know what to do.",
    letterFinalBrand: "In Case",

    guideSteps: "Steps",
    guideNotes: "Notes",
    guideTime: "Est. Time",
    guideDifficulty: "Difficulty",
  },

  accept: {
    title: "You Hold the Spare Key",
    subtitle: "Don't worry — your friend is fine.",
    body: "Someone who trusts you completely has asked you to hold a spare key to the things they've stored here.\n\nThat's all this is. A precaution, like giving a trusted friend a copy of your apartment key. It doesn't mean anything is wrong, and there's nothing to do right now.\n\nIf they ever go quiet for too long — and hopefully they never will — we'll let you know. The key they gave you will let you open what they left behind.",
    confirmButton: "I'll Hold the Key",
    confirmSuccess: "Got it ✓ You hold the spare key now.",
    confirmError: "Confirmation failed. Please try again.",
    invalidLink: "This link is invalid or has expired.",
    whatIsThis: "What is this?",
    whatIsThisAnswer:
      "In Case helps people organize their digital life — accounts, memories, and important notes — and leave a spare key with someone they trust, just in case.",
    alsoPrepare: "Want to set up your own, too?",
    alsoPrepareCta: "Try In Case →",
  },

  credential: {
    createTitle: "Add Trusted Contact",
    editTitle: "Edit Contact",
    nameLabel: "Name",
    namePlaceholder: "e.g. Mom, David",
    emailLabel: "Email",
    emailPlaceholder: "Contact's email",
    phoneLabel: "Phone (optional)",
    phonePlaceholder: "Contact's phone number",
    relationLabel: "Relationship",
    relationPlaceholder: "e.g. Family, Best friend",
    vaultScopeLabel: "Accessible Content",
    vaultScopeDesc: "Select which items this contact can access.",
    selectAll: "Select All",
    deselectAll: "Clear All",
    createButton: "Add Contact",
    updateButton: "Save Changes",
    deleteButton: "Remove Contact",
    deleteConfirm:
      "Remove this contact? They will no longer be able to access your content.",
    created: "Contact added — invitation sent ✓",
    updated: "Contact updated ✓",
    revoked: "Contact removed ✓",

    qrShareLinkCopied: "Link copied",
    qrShareTitle: "Spare Key · Generated",
    qrShareTo: "To",
    qrShareMessenger: "Trusted Contact",
    qrShareLinkSection: "Part 1 · Access Link",
    qrShareLinkDesc: "This link is the key. Share it securely with your trusted contact.",
    qrSharePwdSection: "Part 2 · Decryption Password",
    qrSharePwdPart1: "The password you set when saving your content.",
    qrSharePwdPart2: "They'll need this password to decrypt after opening the link.",
    qrShareBothRequired: "Both parts are required. One without the other is useless.",
    qrShareBothDesc: "A link without a password is like a key without a lock.",
    qrShareAcknowledged: "Understood",
    qrShareCopiedLabel: "Copied",
    qrShareCopyLink: "Copy Link",
  },

  // ============================================================
  // 保险库 VaultList
  // ============================================================
  vault: {
    decryptPrompt: "Enter decryption password",
    decryptError: "Incorrect password — cannot decrypt",
    deleteSuccess: "Deleted",
    deleteError: "Delete failed",
    entryCount: "📦 Vault · {n} saved",
    unnamed: "Untitled",
    decryptPlaceholder: "Enter password to view",
    hide: "Hide",
  },

  crypto: {
    encrypting: "Encrypting…",
    decrypting: "Decrypting…",
    passwordTooShort: "Password must be at least 4 characters",
    passwordsDontMatch: "Passwords don't match",
    setPassword: "Set Password",
    confirmPassword: "Confirm Password",
    passwordHint:
      "Remember your password carefully. It is never uploaded and cannot be recovered if forgotten.",
    generatingKey: "Generating key…",
    keyGenerated: "Key generated ✓",
    generatePassword: "Random password generated — please save it somewhere safe!",
    saved: "Saved",
    encryptTitle: "Encrypt & Save",
    encryptDesc: "Your content will be encrypted with AES-256-GCM in your browser before uploading. The server never sees the plaintext.",
    generateBtn: "Generate Random Password",
    orManual: "or enter manually",
    setPwdLabel: "Set Decryption Password",
    pwdReuse: "(reusing previous password)",
    pwdPlaceholder: "At least 4 characters",
    confirmPlaceholder: "Re-enter password",
    pwdWarning: "⚠️ Remember this password. The person you trust will need it to decrypt. In Case never stores your password on our servers. If you forget it, no one — including you — will ever be able to decrypt this content.",
    saving: "Encrypting & saving…",
    saveBtn: "Encrypt & Save",
    storedEncrypted: "Encrypted · For your eyes only",
  },

  notify: {
    messengerInviteSMS: `A message from In Case:
{label} has asked you to hold a spare key for them —
because you're the person they trust most.

There's nothing to do right now.
If they ever go quiet for too long, we'll let you know — and the key they gave you will unlock what they've left behind.
This is just a precaution. Nothing is wrong.

Accept: {acceptUrl}`,

    messengerInviteEmailSubject:
      "[In Case] You hold a spare key for someone",
    messengerInviteEmailBody: `Hi,

A message from In Case.
Someone who trusts you{label} has asked you to hold a spare key for them.

There's nothing to do right now. If they ever go quiet for too long, we'll let you know — and the key they gave you will let you open what they've left behind.
This is just a precaution. Nothing is wrong.

Confirmation link: {acceptUrl}

In Case · Keep a Spare Key, Just in Case`,

    deadLetterSMS: `A message from In Case:
Someone who trusts you has left something in your care.
It's time to open it.

Reply 1: They're fine — just forgot to check in
Reply 2: I genuinely can't reach them

No reply within 72 hours will result in automatic delivery.`,

    deadLetterReminder24h: `[In Case] Quick reminder: someone left something for you.
It's ready when you are.

Reply 1: They're fine — just forgot to check in
Reply 2: I can't reach them

No reply within 48 hours will result in automatic delivery.`,

    deadLetterReminder48h: `[In Case] Last call: your friend's spare key is ready.

Reply 1: They're fine — renew
Reply 2: Can't reach them — deliver

No reply within 24 hours will result in automatic delivery.`,

    messengerReply1SMS:
      "[In Case] Received — thank you. They're safe, and their protection has been renewed. Have a good day.",
    messengerReply2SMS:
      "[In Case] Thank you. Here's what they left for you:\n{unlockUrl}\nUse the password they gave you to open it.",
    messengerAutoDeliverSMS:
      "[In Case] The spare key your friend left you is ready.\nHere you go:\n{unlockUrl}\nUse the password they gave you to open it.",
    userRenewedByMessengerSMS:
      "[In Case] Your trusted contact confirmed you're well. Your protection has been renewed. All is good.",

    // User pre-expiry warning
    userPreExpiryWarning: "[In Case] Heads up: your digital protection has {daysRemaining} days left. Visit {appUrl} soon to renew — otherwise your trusted contacts will be notified.",
    userPreExpiryWarningSubject: "[In Case] Your protection is about to expire",
    userPreExpiryWarningBody: `Hi,

Your digital protection for In Case has entered the warning period — only {daysRemaining} days remaining.
Please visit {appUrl} soon to check in and renew your protection.

In Case · Keep a Spare Key, Just in Case`,

    smsChannel: "SMS",
    emailChannel: "Email",
    notifySentTo: "{channel} notification sent to {target}",
    demoMode:
      "Demo mode: {channel} notification output to console",
  },

  aiInventory: {
    start: `Hey there 👋

It takes courage to do this — to pause and think about what your digital life will leave behind. That's something worth honoring.

Let me start with a simple question:

**Which app or platform do you spend the most time on?**

(Instagram, Twitter, YouTube, Steam, Gmail — anything at all)`,

    askCategory: `Got it! Let's start from there —

Pick a category you'd like to go through first:

📱 **Social Media** — Instagram, Twitter, TikTok, Facebook, Discord…
💰 **Finance & Payments** — PayPal, banking apps, investments…
🎮 **Entertainment** — Steam, Netflix, Spotify, cloud storage…
✍️ **Creative Work** — YouTube channel, blog, portfolio, newsletter…
📦 **Other** — Domains, crypto, photos, subscriptions…

Where do you want to start?`,

    inventorySocial: `Great, let's start with social media!

Let's go one by one. **Your main Instagram/Twitter account** — what would you want to happen with it?

• Transfer to family or a friend?
• Memorialize (keep visible but frozen)?
• Delete entirely?
• Or… not sure yet?

(No pressure — "not sure yet" is a perfectly fine answer)`,

    inventorySocial2: `Got it. What about **any secondary accounts** — side projects, alt accounts, creator profiles?

• Are you mainly sharing your life?
• Mainly consuming content?
• Or creating content?

This affects how to handle each one.`,

    inventoryPayment: `Good, I've noted that. Now the money stuff 💰

**PayPal, Venmo, banking apps** — these involve real identity. Who would you trust to handle them?

Most people choose their closest family member. What about you?`,

    inventoryEntertainment: `Noted ✍️ Now the fun stuff —

Do you game? Steam, Switch, PlayStation, mobile games… any accounts you'd genuinely care about?

(Like "my Steam library is worth thousands" or "I've spent years building this world" 😄)`,

    inventoryOther: `Ha, I get it! What about —

• Cloud storage (Google Drive, Dropbox — photos, documents)
• Email accounts (Gmail, Outlook)
• Subscriptions (streaming, music, cloud services)

Anything in there that feels important?`,

    summary:
      "Amazing work! You've done something genuinely important ✨ Here's your digital asset inventory:",
    summaryText:
      "Look at that — you've left footprints across at least 8 platforms. Some hold memories, some hold money, some are just habit — but they're all traces of a life lived digitally. Feels a bit more organized now, doesn't it?",
    suggestions:
      "Consider sharing this inventory with someone you trust, and updating it every six months. Some platforms have legacy contact features you can set up now.",
  },

  aiLetter: {
    start: `Writing a letter to someone important — you've probably been thinking about this for a while.

Don't worry about getting it perfect. Let's start with the basics:

**Who is this for?**

(Anyone at all — family, a friend, a partner, even your future self)`,

    askRelationship: `Okay. And what's your relationship to them?

No need to be formal — just say it your way.
Like: "My childhood best friend," "My dad, who I've never really known how to talk to," "The teacher who changed my life."`,

    askMemory: `Thank you for sharing that.

Now, think back: **What's one moment with them you'll never forget?**

It doesn't have to be dramatic. Maybe a meal you shared. A throwaway comment. A tiny gesture. But years later, it's still with you.`,

    askUnsaid: `That moment really matters. Thank you for telling me about it.

Now, I'd like to ask something a little harder —

**What's something you've always wanted to say to them, but never have?**

Maybe it's "Thank you." Maybe it's "I'm sorry." Maybe it's "I've always looked up to you." Or something else entirely.`,

    draftReady:
      "Here's a draft for you 💌 Edit, copy, or ask me to write another version.",
    regenerateMessage: "Here's a different version — let me know what you think.",
  },

  api: {
    notFound: "Not found",
    unauthorized: "Unauthorized — please sign in",
    badRequest: "Invalid request parameters",
    serverError: "Server error — please try again later",
    rateLimit: "Too many attempts — please try again later",

    codeSent: "Verification code sent",
    codeExpired: "Verification code expired",
    codeInvalid: "Invalid verification code",
    codeSentTooFrequent:
      "Code sent too frequently — please wait before requesting again",
    loginSuccess: "Signed in successfully",
    bindSuccess: "Identity linked successfully",
    alreadyBound: "This phone/email is already linked to an account",

    vaultNotFound: "Vault item not found",
    vaultCreated: "Vault item created",
    vaultUpdated: "Vault item updated",
    vaultDeleted: "Vault item deleted",
    encryptionFailed: "Encryption failed",
    decryptionFailed: "Decryption failed",

    credentialNotFound: "Credential not found",
    credentialRevoked: "Credential revoked",
    credentialCreated: "Credential created",
    credentialUpdated: "Credential updated",
    tooManyAttempts: "Too many attempts",
    accessDenied: "Access denied",

    deadlineNotReached: "Protection threshold has not been reached",
    deadLetterTriggered: "Protection threshold notification triggered",
    renewalConfirmed: "Renewal confirmed",
    autoDelivered: "Auto-delivered",

    exportSuccess: "Export successful",
    importSuccess: "Import successful",
    importFailed: "Import failed — invalid file format",
    importPartial:
      "Partial import: {success} succeeded, {failed} failed",

    credentialInvalid: "Credential is invalid or expired",
    passwordRequired: "Decryption password is required",
    passwordWrong: "Incorrect password",
  },
  legal: {
    cookieConsentTitle: "Cookie Notice",
    cookieConsentBody:
      "We use essential cookies to recognize your device and keep you logged in. No third-party tracking or advertising cookies are used. By continuing, you consent to this.",
    cookieAccept: "Got it",
    cookieLearnMore: "Learn more",

    // ─── Privacy Policy ───────────────────────────────
    privacyTitle: "Privacy Policy",
    privacyLastUpdated: "Last updated: June 17, 2026",
    privacyIntro:
      'In Case ("we," "us," or "our") values your privacy. This Privacy Policy explains how we collect, use, and protect your information when you use our service.',
    privacyInfoWeCollect:
      "Information we collect: (a) Contact information — phone number and/or email address you provide for identity verification and notification alerts. (b) Encrypted content — asset inventories and letter drafts, encrypted in your browser using AES-256-GCM before upload; we cannot and do not access plaintext. (c) Account metadata — subscription status, protection threshold settings, and trusted contact relationships. (d) Essential cookies — a session token to recognize your device and keep you signed in.",
    privacyHowWeUse:
      "How we use your information: (a) To verify your identity and restore your account across devices. (b) To send notification alerts (SMS/email) when your protection threshold is reached. (c) To process subscriptions and maintain your account. (d) To communicate service updates or critical security notices. We do NOT use your information for advertising, user profiling, or automated decision-making.",
    privacySMSData:
      "SMS / Text Messaging: If you provide a phone number, we use it solely for identity verification and delivering notification alerts. With your explicit consent, we may send SMS messages including verification codes, spare key invitations, and protection threshold alerts. Message frequency varies and is typically low (a few messages per month). Message and data rates may apply as determined by your mobile carrier. You may opt out of SMS at any time by replying STOP to any message or updating your settings. After opting out, we will only send a single confirmation message and will not contact you via SMS again unless you re-enroll.",
    privacyDataSharing:
      "Data sharing & disclosure: We do NOT sell, rent, trade, or share your personal information — including your phone number, email address, and SMS opt-in data — with any third party for their marketing or promotional purposes. We may share information only: (a) with service providers (e.g., Twilio for SMS delivery, Resend for email delivery, Supabase for database hosting) who are contractually bound to use your data solely to provide services to us; (b) if required by law, court order, or government regulation; (c) to protect our rights, property, or safety. All service providers are GDPR and CCPA compliant.",
    privacyDataRetention:
      "Data retention: We retain your account information for as long as your account is active. Encrypted content is stored until you delete it. If you delete your account, all associated data is permanently removed within 30 days. Log data is retained for a maximum of 90 days.",
    privacyYourRights:
      "Your rights: Depending on your jurisdiction, you may have the right to: access the personal data we hold about you; correct inaccurate data; delete your account and all associated data; export your data in a portable format; withdraw consent for SMS/email communications at any time; lodge a complaint with your local data protection authority. To exercise these rights, contact us at privacy@in-case.me.",
    privacyGDPR:
      "GDPR & CCPA compliance: We comply with the EU General Data Protection Regulation (GDPR) and the California Consumer Privacy Act (CCPA). Under GDPR, our lawful basis for processing your contact information is your explicit consent and our legitimate interest in providing the service. We do not sell personal data as defined by CCPA. EU users have the right to data portability and the right to be forgotten. You may designate an authorized agent to submit requests on your behalf.",
    privacyChildren:
      "Children's privacy: In Case is not directed to individuals under the age of 16. We do not knowingly collect personal information from children. If we become aware that a child under 16 has provided us with personal data, we will delete it promptly.",
    privacyContact:
      "Contact: For privacy-related inquiries, to exercise your data rights, or to report a security vulnerability, please email privacy@in-case.me. Response time is typically within 48 hours.",

    // ─── Terms of Service ──────────────────────────────
    termsTitle: "Terms of Service",
    termsLastUpdated: "Last updated: June 17, 2026",
    termsIntro:
      "Welcome to In Case. By accessing or using our website and services, you agree to be bound by these Terms of Service. If you do not agree, please discontinue use immediately.",
    termsEligibility:
      "Eligibility: You must be at least 16 years old to use In Case. By creating an account, you represent that you are of legal age and have the capacity to enter into a binding agreement. If you are using the service on behalf of an organization, you represent that you have the authority to bind that organization to these terms.",
    termsAccount:
      "Account & security: You are responsible for maintaining the confidentiality of your account credentials and decryption password. In Case operates a zero-knowledge architecture — your password is never transmitted to our servers and cannot be recovered if lost. You are responsible for all activities that occur under your account. Notify us immediately of any unauthorized use.",
    termsSMS:
      "SMS / Text messaging: By providing your phone number, you give express written consent to receive SMS messages from In Case, including: identity verification codes, spare key invitations and status updates, protection threshold notifications, and critical account alerts. Message frequency varies (typically 1–10 messages per month). Message and data rates may apply based on your mobile carrier plan. You are not required to consent to SMS as a condition of purchase. To opt out at any time, reply STOP to any message. After opting out, you will receive one confirmation message. For help, reply HELP or contact support@in-case.me. Participating carriers include but are not limited to AT&T, T-Mobile, Verizon, and their affiliates. We are not liable for delayed or undelivered messages due to carrier filtering or network conditions.",
    termsSubscription:
      "Subscriptions & billing: In Case offers annual subscriptions ($23/year) and lifetime access ($198 one-time). All prices are in US dollars. Annual subscriptions auto-renew unless canceled at least 24 hours before the renewal date. You may cancel auto-renewal at any time from your account settings. Paid subscription fees are non-refundable except as required by applicable law or as described in our Refund Policy. We reserve the right to change pricing with 30 days' notice; price changes do not affect active subscriptions until renewal.",
    termsRefund:
      "Refund policy: Annual subscriptions may be eligible for a full refund within 14 days of the initial purchase or renewal if no notification alerts have been triggered. Lifetime purchases are final and non-refundable. To request a refund, contact support@in-case.me with your account details. Refunds are processed within 5–10 business days to the original payment method. See our full Refund Policy page for details.",
    termsDisclaimer:
      "Legal disclaimer: In Case is a digital asset planning and organization tool. It is NOT a law firm and does NOT provide legal, financial, or tax advice. No content generated by this product — including asset inventories, platform access guides, or letter drafts — constitutes a legal document, living will, or testamentary instrument. For matters involving significant legal rights or financial obligations, consult a licensed professional in your jurisdiction.",
    termsLiability:
      "Limitation of liability: To the fullest extent permitted by applicable law, In Case and its operators shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from or relating to your use of the service, including but not limited to: data loss or corruption; notification delays, failures, or misdelivery; third-party service interruptions (e.g., SMS carriers, cloud providers, payment processors); unauthorized access to your account due to your failure to secure your credentials. Our aggregate liability for any claim shall not exceed the amount you have paid us in the 12 months preceding the claim.",
    termsTermination:
      "Termination: You may stop using In Case and delete your account at any time from the Settings page. We may suspend or terminate your account if you violate these terms, engage in illegal activity, or if your account remains inactive for an extended period after reasonable notice. Upon termination, your encrypted data will be permanently deleted within 30 days.",
    termsChanges:
      "Changes to terms: We may update these terms from time to time. We will notify you of material changes via email or through the service at least 30 days in advance. Continued use after the effective date constitutes acceptance of the updated terms. The latest version is always available at in-case.me/terms.",
    termsContact:
      "Contact: For questions about these terms, contact support@in-case.me.",

    // ─── Refund Policy ─────────────────────────────────
    refundTitle: "Refund Policy",
    refundLastUpdated: "Last updated: June 17, 2026",
    refundIntro:
      "We want you to be satisfied with In Case. This policy outlines when and how refunds are issued.",
    refundAnnual:
      "Annual subscriptions ($23/year): You may request a full refund within 14 calendar days of your initial purchase or renewal, provided that no notification process has been triggered on your account. Refund requests after 14 days are handled on a case-by-case basis at our discretion.",
    refundLifetime:
      "Lifetime access ($198): Lifetime purchases are final and non-refundable. This is a one-time payment that provides access for the lifetime of the service. By purchasing lifetime access, you acknowledge and accept this policy.",
    refundProcess:
      "How to request a refund: Email support@in-case.me with your registered email address and the reason for your request. We process approved refunds within 5–10 business days to the original payment method. You will receive email confirmation once the refund has been issued.",
    refundExceptions:
      "Exceptions: Nothing in this policy limits any statutory refund rights you may have under applicable consumer protection laws in your jurisdiction. If you believe you qualify for a refund under local law, please contact us and we will review your request.",
    refundContact:
      "Questions? Reach us at support@in-case.me.",

    // ─── FAQ ───────────────────────────────────────────
    faqTitle: "FAQ",
    faqLastUpdated: "Last updated: June 2026",
  },
};

export default en;
